Jan 12 12:13:19 demo-worker kubelet[227]: I0112 12:13:19.862454     227 pod_startup_latency_tracker.go:104] "Observed pod startup duration" pod="kube-system/kindnet-pzg45" podStartSLOduration=2.862435588 podStartE2EDuration="2.862435588s" podCreationTimestamp="2025-01-12 12:13:17 +0000 UTC" firstStartedPulling="0001-01-01 00:00:00 +0000 UTC" lastFinishedPulling="0001-01-01 00:00:00 +0000 UTC" observedRunningTime="2025-01-12 12:13:19.857866505 +0000 UTC m=+2.074788127" watchObservedRunningTime="2025-01-12 12:13:19.862435588 +0000 UTC m=+2.079357168"
Jan 12 12:13:30 demo-worker kubelet[227]: I0112 12:13:30.324072     227 kubelet_node_status.go:497] "Fast updating node status as it just became ready"
Jan 12 12:15:50 demo-worker kubelet[227]: E0112 12:15:50.566294     227 kubelet_node_status.go:544] "Error updating node status, will retry" err="error getting node \"demo-worker\": Get \"https://demo-control-plane:6443/api/v1/nodes/demo-worker?resourceVersion=0&timeout=10s\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)"


Jan 12 12:15:50 demo-worker kubelet[227]: E0112 12:15:50.797249     227 controller.go:195] "Failed to update lease" err="Put \"https://demo-control-plane:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/demo-worker?timeout=10s\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
Jan 12 12:15:51 demo-worker kubelet[227]: I0112 12:15:51.297202     227 scope.go:117] "RemoveContainer" containerID="27623120872cd68cde0e7e38c5e3be2b7ca0f20de7a8b70622b0160934f08315"
Jan 12 12:16:00 demo-worker kubelet[227]: E0112 12:16:00.567783     227 kubelet_node_status.go:544] "Error updating node status, will retry" err="error getting node \"demo-worker\": Get \"https://demo-control-plane:6443/api/v1/nodes/demo-worker?timeout=10s\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
Jan 12 12:16:00 demo-worker kubelet[227]: E0112 12:16:00.799661     227 controller.go:195] "Failed to update lease" err="Put \"https://demo-control-plane:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/demo-worker?timeout=10s\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)"


Jan 12 12:16:10 demo-worker kubelet[227]: E0112 12:16:10.567154     227 kubelet_node_status.go:544] "Error updating node status, will retry" err="error getting node \"demo-worker\": Get \"https://demo-control-plane:6443/api/v1/nodes/demo-worker?timeout=10s\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
Jan 12 12:16:10 demo-worker kubelet[227]: E0112 12:16:10.800256     227 controller.go:195] "Failed to update lease" err="Put \"https://demo-control-plane:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/demo-worker?timeout=10s\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
Jan 12 12:16:15 demo-worker kubelet[227]: W0112 12:16:15.511493     227 reflector.go:470] object-"kube-system"/"kube-root-ca.crt": watch of *v1.ConfigMap ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
Jan 12 12:16:15 demo-worker kubelet[227]: E0112 12:16:15.511545     227 controller.go:195] "Failed to update lease" err="Put \"https://demo-control-plane:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/demo-worker?timeout=10s\": http2: client connection lost"
Jan 12 12:16:15 demo-worker kubelet[227]: E0112 12:16:15.511812     227 kubelet_node_status.go:544] "Error updating node status, will retry" err="error getting node \"demo-worker\": Get \"https://demo-control-plane:6443/api/v1/nodes/demo-worker?timeout=10s\": http2: client connection lost"
Jan 12 12:16:15 demo-worker kubelet[227]: I0112 12:16:15.511793     227 status_manager.go:853] "Failed to get status for pod" podUID="77645c86-7e44-4b4c-81fa-f476952ba593" pod="kube-system/kindnet-pzg45" err="Get \"https://demo-control-plane:6443/api/v1/namespaces/kube-system/pods/kindnet-pzg45\": http2: client connection lost"
Jan 12 12:16:15 demo-worker kubelet[227]: W0112 12:16:15.511589     227 reflector.go:470] k8s.io/client-go/informers/factory.go:160: watch of *v1.Service ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
Jan 12 12:16:15 demo-worker kubelet[227]: W0112 12:16:15.511515     227 reflector.go:470] pkg/kubelet/config/apiserver.go:66: watch of *v1.Pod ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
Jan 12 12:16:15 demo-worker kubelet[227]: W0112 12:16:15.511554     227 reflector.go:470] k8s.io/client-go/informers/factory.go:160: watch of *v1.Node ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
Jan 12 12:16:15 demo-worker kubelet[227]: W0112 12:16:15.511615     227 reflector.go:470] k8s.io/client-go/informers/factory.go:160: watch of *v1.CSIDriver ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
Jan 12 12:16:15 demo-worker kubelet[227]: W0112 12:16:15.511690     227 reflector.go:470] k8s.io/client-go/informers/factory.go:160: watch of *v1.RuntimeClass ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
Jan 12 12:16:15 demo-worker kubelet[227]: E0112 12:16:15.511835     227 event.go:368] "Unable to write event (may retry after sleeping)" err="Patch \"https://demo-control-plane:6443/api/v1/namespaces/kube-system/events/kindnet-pzg45.1819f0e5604c64fd\": http2: client connection lost" event="&Event{ObjectMeta:{kindnet-pzg45.1819f0e5604c64fd  kube-system   468 0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] [] []},InvolvedObject:ObjectReference{Kind:Pod,Namespace:kube-system,Name:kindnet-pzg45,UID:77645c86-7e44-4b4c-81fa-f476952ba593,APIVersion:v1,ResourceVersion:450,FieldPath:spec.containers{kindnet-cni},},Reason:Pulled,Message:Container image \"docker.io/kindest/kindnetd:v20240813-c6f155d6\" already present on machine,Source:EventSource{Component:kubelet,Host:demo-worker,},FirstTimestamp:2025-01-12 12:13:19 +0000 UTC,LastTimestamp:2025-01-12 12:15:51.298503297 +0000 UTC m=+153.517644446,Count:2,Type:Normal,EventTime:0001-01-01 00:00:00 +0000 UTC,Series:nil,Action:,Related:nil,ReportingController:kubelet,ReportingInstance:demo-worker,}"
Jan 12 12:16:15 demo-worker kubelet[227]: W0112 12:16:15.511745     227 reflector.go:470] object-"kube-system"/"kube-proxy": watch of *v1.ConfigMap ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
Jan 12 12:16:15 demo-worker kubelet[227]: E0112 12:16:15.512743     227 kubelet_node_status.go:544] "Error updating node status, will retry" err="error getting node \"demo-worker\": Get \"https://demo-control-plane:6443/api/v1/nodes/demo-worker?timeout=10s\": dial tcp: lookup demo-control-plane on 192.168.65.254:53: dial udp 192.168.65.254:53: connect: network is unreachable"
Jan 12 12:16:15 demo-worker kubelet[227]: E0112 12:16:15.512779     227 kubelet_node_status.go:531] "Unable to update node status" err="update node status exceeds retry count"
Jan 12 12:16:15 demo-worker kubelet[227]: I0112 12:16:15.512883     227 status_manager.go:853] "Failed to get status for pod" podUID="77645c86-7e44-4b4c-81fa-f476952ba593" pod="kube-system/kindnet-pzg45" err="Get \"https://demo-control-plane:6443/api/v1/namespaces/kube-system/pods/kindnet-pzg45\": dial tcp: lookup demo-control-plane on 192.168.65.254:53: dial udp 192.168.65.254:53: connect: network is unreachable"
Jan 12 12:16:15 demo-worker kubelet[227]: E0112 12:16:15.512891     227 controller.go:195] "Failed to update lease" err="Put \"https://demo-control-plane:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/demo-worker?timeout=10s\": dial tcp: lookup demo-control-plane on 192.168.65.254:53: dial udp 192.168.65.254:53: connect: network is unreachable"
Jan 12 12:16:15 demo-worker kubelet[227]: I0112 12:16:15.512969     227 controller.go:115] "failed to update lease using latest lease, fallback to ensure lease" err="failed 5 attempts to update lease"
Jan 12 12:16:15 demo-worker kubelet[227]: I0112 12:16:15.513351     227 status_manager.go:853] "Failed to get status for pod" podUID="77645c86-7e44-4b4c-81fa-f476952ba593" pod="kube-system/kindnet-pzg45" err="Get \"https://demo-control-plane:6443/api/v1/namespaces/kube-system/pods/kindnet-pzg45\": dial tcp: lookup demo-control-plane on 192.168.65.254:53: dial udp 192.168.65.254:53: connect: network is unreachable"
Jan 12 12:16:15 demo-worker kubelet[227]: E0112 12:16:15.513443     227 controller.go:145] "Failed to ensure lease exists, will retry" err="Get \"https://demo-control-plane:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/demo-worker?timeout=10s\": dial tcp: lookup demo-control-plane on 192.168.65.254:53: dial udp 192.168.65.254:53: connect: network is unreachable" interval="200ms"
Jan 12 12:16:15 demo-worker kubelet[227]: E0112 12:16:15.714758     227 controller.go:145] "Failed to ensure lease exists, will retry" err="Get \"https://demo-control-plane:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/demo-worker?timeout=10s\": dial tcp: lookup demo-control-plane on 192.168.65.254:53: dial udp 192.168.65.254:53: connect: network is unreachable" interval="400ms"
Jan 12 12:16:16 demo-worker kubelet[227]: E0112 12:16:16.115615     227 controller.go:145] "Failed to ensure lease exists, will retry" err="Get \"https://demo-control-plane:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/demo-worker?timeout=10s\": dial tcp: lookup demo-control-plane on 192.168.65.254:53: dial udp 192.168.65.254:53: connect: network is unreachable" interval="800ms"
Jan 12 12:16:16 demo-worker kubelet[227]: W0112 12:16:16.438446     227 reflector.go:547] k8s.io/client-go/informers/factory.go:160: failed to list *v1.RuntimeClass: Get "https://demo-control-plane:6443/apis/node.k8s.io/v1/runtimeclasses?resourceVersion=677": dial tcp: lookup demo-control-plane on 192.168.65.254:53: dial udp 192.168.65.254:53: connect: network is unreachable
Jan 12 12:16:16 demo-worker kubelet[227]: E0112 12:16:16.438540     227 reflector.go:150] k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.RuntimeClass: failed to list *v1.RuntimeClass: Get "https://demo-control-plane:6443/apis/node.k8s.io/v1/runtimeclasses?resourceVersion=677": dial tcp: lookup demo-control-plane on 192.168.65.254:53: dial udp 192.168.65.254:53: connect: network is unreachable
Jan 12 12:16:16 demo-worker kubelet[227]: W0112 12:16:16.468887     227 reflector.go:547] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Service: Get "https://demo-control-plane:6443/api/v1/services?resourceVersion=681": dial tcp: lookup demo-control-plane on 192.168.65.254:53: dial udp 192.168.65.254:53: connect: network is unreachable
Jan 12 12:16:16 demo-worker kubelet[227]: E0112 12:16:16.469020     227 reflector.go:150] k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://demo-control-plane:6443/api/v1/services?resourceVersion=681": dial tcp: lookup demo-control-plane on 192.168.65.254:53: dial udp 192.168.65.254:53: connect: network is unreachable
Jan 12 12:16:16 demo-worker kubelet[227]: W0112 12:16:16.699097     227 reflector.go:547] k8s.io/client-go/informers/factory.go:160: failed to list *v1.CSIDriver: Get "https://demo-control-plane:6443/apis/storage.k8s.io/v1/csidrivers?resourceVersion=681": dial tcp: lookup demo-control-plane on 192.168.65.254:53: dial udp 192.168.65.254:53: connect: network is unreachable
Jan 12 12:16:16 demo-worker kubelet[227]: E0112 12:16:16.699243     227 reflector.go:150] k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: Get "https://demo-control-plane:6443/apis/storage.k8s.io/v1/csidrivers?resourceVersion=681": dial tcp: lookup demo-control-plane on 192.168.65.254:53: dial udp 192.168.65.254:53: connect: network is unreachable
Jan 12 12:16:16 demo-worker kubelet[227]: W0112 12:16:16.718401     227 reflector.go:547] object-"kube-system"/"kube-root-ca.crt": failed to list *v1.ConfigMap: Get "https://demo-control-plane:6443/api/v1/namespaces/kube-system/configmaps?fieldSelector=metadata.name%3Dkube-root-ca.crt&resourceVersion=681": dial tcp: lookup demo-control-plane on 192.168.65.254:53: dial udp 192.168.65.254:53: connect: network is unreachable
Jan 12 12:16:16 demo-worker kubelet[227]: E0112 12:16:16.718510     227 reflector.go:150] object-"kube-system"/"kube-root-ca.crt": Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: Get "https://demo-control-plane:6443/api/v1/namespaces/kube-system/configmaps?fieldSelector=metadata.name%3Dkube-root-ca.crt&resourceVersion=681": dial tcp: lookup demo-control-plane on 192.168.65.254:53: dial udp 192.168.65.254:53: connect: network is unreachable
Jan 12 12:16:16 demo-worker kubelet[227]: W0112 12:16:16.750925     227 reflector.go:547] pkg/kubelet/config/apiserver.go:66: failed to list *v1.Pod: Get "https://demo-control-plane:6443/api/v1/pods?fieldSelector=spec.nodeName%3Ddemo-worker&resourceVersion=681": dial tcp: lookup demo-control-plane on 192.168.65.254:53: dial udp 192.168.65.254:53: connect: network is unreachable
Jan 12 12:16:16 demo-worker kubelet[227]: E0112 12:16:16.751069     227 reflector.go:150] pkg/kubelet/config/apiserver.go:66: Failed to watch *v1.Pod: failed to list *v1.Pod: Get "https://demo-control-plane:6443/api/v1/pods?fieldSelector=spec.nodeName%3Ddemo-worker&resourceVersion=681": dial tcp: lookup demo-control-plane on 192.168.65.254:53: dial udp 192.168.65.254:53: connect: network is unreachable
Jan 12 12:16:16 demo-worker kubelet[227]: W0112 12:16:16.830575     227 reflector.go:547] object-"kube-system"/"kube-proxy": failed to list *v1.ConfigMap: Get "https://demo-control-plane:6443/api/v1/namespaces/kube-system/configmaps?fieldSelector=metadata.name%3Dkube-proxy&resourceVersion=681": dial tcp: lookup demo-control-plane on 192.168.65.254:53: dial udp 192.168.65.254:53: connect: network is unreachable
Jan 12 12:16:16 demo-worker kubelet[227]: E0112 12:16:16.830826     227 reflector.go:150] object-"kube-system"/"kube-proxy": Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: Get "https://demo-control-plane:6443/api/v1/namespaces/kube-system/configmaps?fieldSelector=metadata.name%3Dkube-proxy&resourceVersion=681": dial tcp: lookup demo-control-plane on 192.168.65.254:53: dial udp 192.168.65.254:53: connect: network is unreachable
Jan 12 12:16:16 demo-worker kubelet[227]: E0112 12:16:16.916950     227 controller.go:145] "Failed to ensure lease exists, will retry" err="Get \"https://demo-control-plane:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/demo-worker?timeout=10s\": dial tcp: lookup demo-control-plane on 192.168.65.254:53: dial udp 192.168.65.254:53: connect: network is unreachable" interval="1.6s"
Jan 12 12:16:17 demo-worker kubelet[227]: W0112 12:16:17.098877     227 reflector.go:547] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Node: Get "https://demo-control-plane:6443/api/v1/nodes?fieldSelector=metadata.name%3Ddemo-worker&resourceVersion=675": dial tcp: lookup demo-control-plane on 192.168.65.254:53: dial udp 192.168.65.254:53: connect: network is unreachable
Jan 12 12:16:17 demo-worker kubelet[227]: E0112 12:16:17.099110     227 reflector.go:150] k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://demo-control-plane:6443/api/v1/nodes?fieldSelector=metadata.name%3Ddemo-worker&resourceVersion=675": dial tcp: lookup demo-control-plane on 192.168.65.254:53: dial udp 192.168.65.254:53: connect: network is unreachable
Jan 12 12:16:17 demo-worker kubelet[227]: I0112 12:16:17.838938     227 status_manager.go:853] "Failed to get status for pod" podUID="77645c86-7e44-4b4c-81fa-f476952ba593" pod="kube-system/kindnet-pzg45" err="Get \"https://demo-control-plane:6443/api/v1/namespaces/kube-system/pods/kindnet-pzg45\": dial tcp: lookup demo-control-plane on 192.168.65.254:53: dial udp 192.168.65.254:53: connect: network is unreachable"
Jan 12 12:16:18 demo-worker kubelet[227]: W0112 12:16:18.377087     227 reflector.go:547] object-"kube-system"/"kube-root-ca.crt": failed to list *v1.ConfigMap: Get "https://demo-control-plane:6443/api/v1/namespaces/kube-system/configmaps?fieldSelector=metadata.name%3Dkube-root-ca.crt&resourceVersion=681": dial tcp: lookup demo-control-plane on 192.168.65.254:53: dial udp 192.168.65.254:53: connect: network is unreachable
Jan 12 12:16:18 demo-worker kubelet[227]: E0112 12:16:18.377190     227 reflector.go:150] object-"kube-system"/"kube-root-ca.crt": Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: Get "https://demo-control-plane:6443/api/v1/namespaces/kube-system/configmaps?fieldSelector=metadata.name%3Dkube-root-ca.crt&resourceVersion=681": dial tcp: lookup demo-control-plane on 192.168.65.254:53: dial udp 192.168.65.254:53: connect: network is unreachable
Jan 12 12:16:18 demo-worker kubelet[227]: W0112 12:16:18.410768     227 reflector.go:547] k8s.io/client-go/informers/factory.go:160: failed to list *v1.RuntimeClass: Get "https://demo-control-plane:6443/apis/node.k8s.io/v1/runtimeclasses?resourceVersion=677": dial tcp: lookup demo-control-plane on 192.168.65.254:53: dial udp 192.168.65.254:53: connect: network is unreachable
Jan 12 12:16:18 demo-worker kubelet[227]: E0112 12:16:18.410951     227 reflector.go:150] k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.RuntimeClass: failed to list *v1.RuntimeClass: Get "https://demo-control-plane:6443/apis/node.k8s.io/v1/runtimeclasses?resourceVersion=677": dial tcp: lookup demo-control-plane on 192.168.65.254:53: dial udp 192.168.65.254:53: connect: network is unreachable
Jan 12 12:16:18 demo-worker kubelet[227]: W0112 12:16:18.449243     227 reflector.go:547] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Service: Get "https://demo-control-plane:6443/api/v1/services?resourceVersion=681": dial tcp: lookup demo-control-plane on 192.168.65.254:53: dial udp 192.168.65.254:53: connect: network is unreachable
Jan 12 12:16:18 demo-worker kubelet[227]: E0112 12:16:18.449397     227 reflector.go:150] k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://demo-control-plane:6443/api/v1/services?resourceVersion=681": dial tcp: lookup demo-control-plane on 192.168.65.254:53: dial udp 192.168.65.254:53: connect: network is unreachable
Jan 12 12:16:18 demo-worker kubelet[227]: E0112 12:16:18.519007     227 controller.go:145] "Failed to ensure lease exists, will retry" err="Get \"https://demo-control-plane:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/demo-worker?timeout=10s\": dial tcp: lookup demo-control-plane on 192.168.65.254:53: dial udp 192.168.65.254:53: connect: network is unreachable" interval="3.2s"
Jan 12 12:16:18 demo-worker kubelet[227]: W0112 12:16:18.773965     227 reflector.go:547] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Node: Get "https://demo-control-plane:6443/api/v1/nodes?fieldSelector=metadata.name%3Ddemo-worker&resourceVersion=675": dial tcp: lookup demo-control-plane on 192.168.65.254:53: dial udp 192.168.65.254:53: connect: network is unreachable
Jan 12 12:16:18 demo-worker kubelet[227]: E0112 12:16:18.774031     227 reflector.go:150] k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://demo-control-plane:6443/api/v1/nodes?fieldSelector=metadata.name%3Ddemo-worker&resourceVersion=675": dial tcp: lookup demo-control-plane on 192.168.65.254:53: dial udp 192.168.65.254:53: connect: network is unreachable
